/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-12-11 22:45:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import neu.edu.cs5200.*;
import java.util.*;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class SearchByNamenDAO_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/star-rating.min.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/star-rating.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/round-about.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>SearchByName</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\"\r\n");
      out.write("\t\t\t\t\thref=\"http://localhost:8080/neu.edu.cs5200/Login.jsp\">MTG</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"http://localhost:8080/neu.edu.cs5200/Rules.jsp\">Rules</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"http://localhost:8080/neu.edu.cs5200/SearchByName.jsp\">SearchByName</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"http://localhost:8080/neu.edu.cs5200/RandomACard.jsp\">RandomACard</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"http://localhost:8080/neu.edu.cs5200/AveragerRate.jsp\">Top10</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a id=\"login\" href=\"http://localhost:8080/neu.edu.cs5200/Login.jsp\">Log\r\n");
      out.write("\t\t\t\t\t\t\tin</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a>|</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a id=\"logout\" href=\"http://localhost:8080/neu.edu.cs5200/Register.jsp\">Register</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
  

	
	Card card = (Card)request.getAttribute("card");
	if(card!=null){
	CardDAO dao = new CardDAO();
	dao.createCard(card);
	Global.cardname = card.getName();
	Global.cardid = card.getCardid();
	Global.setnumber = card.getSetnumber();
	Global.searchname = card.getSearchname();
	Global.description = card.getDescription();
	Global.flavor = card.getFlavor();
	Global.releasedat = card.getReleasedat();
	Global.colors = card.getColors();
	Global.manacost = card.getManacost();
	Global.convertedmanacost =card.getConvertedmanacost();
	Global.cardsetname = card.getCardsetname();
	Global.type = card.getType();
	Global.subtype = card.getSubtype();
	Global.power = card.getPower();
	Global.relatedcardid = card.getRelatedcardid();
	

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<p> The card's id is");
      out.print( Global.cardid );
      out.write(" </p>\r\n");
      out.write("\t<p> The related card id is");
      out.print( Global.relatedcardid );
      out.write(" </p>\r\n");
      out.write("\t<p> The set number is ");
      out.print( Global.setnumber );
      out.write(" </p>\r\n");
      out.write("\t<p> The Name is ");
      out.print( Global.cardname );
      out.write("</p>\r\n");
      out.write("\t<p> The search name is ");
      out.print( Global.searchname );
      out.write("</p>\r\n");
      out.write("\t<p> ");
      out.print( Global.description );
      out.write("</p>\r\n");
      out.write("\t<p> ");
      out.print( Global.flavor );
      out.write("</p>\r\n");
      out.write("\t<p> The clolor is ");
      out.print( Global.colors );
      out.write("</p>\r\n");
      out.write("\t<p> The mana cost is ");
      out.print( Global.manacost );
      out.write("</p>\r\n");
      out.write("\t<p> The converted mana cost is ");
      out.print( Global.convertedmanacost );
      out.write("</p>\r\n");
      out.write("\t<p> Card set name : ");
      out.print( Global.cardsetname );
      out.write("</p>\r\n");
      out.write("\t<p> Type : ");
      out.print( Global.type );
      out.write("</p>\r\n");
      out.write("\t<p> Subtype : ");
      out.print( Global.subtype );
      out.write("</p>\r\n");
      out.write("\t<p> Power : ");
      out.print( Global.power );
      out.write(" </p>\r\n");
      out.write("\t<p><img alt=\"\" src=\"http://api.mtgdb.info/content/card_images/");
      out.print( Global.cardid );
      out.write(".jpeg\"></p>\r\n");
}else{ 
      out.write("\r\n");
      out.write("<p> The card's id is");
      out.print( Global.cardid );
      out.write(" </p>\r\n");
      out.write("\t<p> The related card id is");
      out.print( Global.relatedcardid );
      out.write(" </p>\r\n");
      out.write("\t<p> The set number is ");
      out.print( Global.setnumber );
      out.write(" </p>\r\n");
      out.write("\t<p> The Name is ");
      out.print( Global.cardname );
      out.write("</p>\r\n");
      out.write("\t<p> The search name is ");
      out.print( Global.searchname );
      out.write("</p>\r\n");
      out.write("\t<p> ");
      out.print( Global.description );
      out.write("</p>\r\n");
      out.write("\t<p> ");
      out.print( Global.flavor );
      out.write("</p>\r\n");
      out.write("\t<p> The clolor is ");
      out.print( Global.colors );
      out.write("</p>\r\n");
      out.write("\t<p> The mana cost is ");
      out.print( Global.manacost );
      out.write("</p>\r\n");
      out.write("\t<p> The converted mana cost is ");
      out.print( Global.convertedmanacost );
      out.write("</p>\r\n");
      out.write("\t<p> Card set name : ");
      out.print( Global.cardsetname );
      out.write("</p>\r\n");
      out.write("\t<p> Type : ");
      out.print( Global.type );
      out.write("</p>\r\n");
      out.write("\t<p> Subtype : ");
      out.print( Global.subtype );
      out.write("</p>\r\n");
      out.write("\t<p> Power : ");
      out.print( Global.power );
      out.write(" </p>\r\n");
      out.write("\t<p><img alt=\"\" src=\"http://api.mtgdb.info/content/card_images/");
      out.print( Global.cardid );
      out.write(".jpeg\"></p>\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

RateDAO rdao = new RateDAO();

String action = request.getParameter("action");
String name = request.getParameter("name");
if("update".equals(action)){

double num = Double.parseDouble(name);
Timestamp date = new Timestamp(System.currentTimeMillis());
Rate r = new Rate(Global.username,Global.cardname,num,date);
rdao.createRate(r);
AverageRateDAO dao = new AverageRateDAO();
dao.deleteAverageRate();
AverageRateDAO dao1 = new AverageRateDAO();
dao1.CalculateRate();
AverageRateDAO dao2 = new AverageRateDAO();
dao2.Output();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"SearchByNamenDAO.jsp\">\r\n");
      out.write("<div class=\"container col-lg-4 col-lg-offset-4\" Style=\"margin-top: 10px\">\r\n");
      out.write("\r\n");
      out.write("\t\t<input name=\"name\" class=\"form-control\" placeholder=\"Please enter number from 0 to 5\"/>\r\n");
      out.write("\t\t<button name=\"action\" value=\"update\" class=\"btn btn-primary\" >Rate</button>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<form action=\"/neu.edu.cs5200/AddAction\">\r\n");
      out.write("\r\n");
      out.write("\t<button class=\"btn btn-primary\" >AddToFavourite</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
CommentDAO cdao = new CommentDAO();
				UserDAO udao = new UserDAO();
		
				String idStr = request.getParameter("id");
				List<Comment> comments = cdao.findCommentByCardname(Global.cardname);
				
				for(Comment dir:comments) {
					User user = udao.findUserbyUsername(dir.getUsername());
					//Global.comment =dir.getComment();
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("<form action=\"/neu.edu.cs5200/CommentDelete\">\r\n");
      out.write("<div class=\"panel panel-info\" style=\"margin: 100px 40px 0px 40px\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">Comment</div>\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">CommentTitle</div>\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<p>");
      out.print( dir.getComment());
      out.write("</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t<li class=\"list-group-item\"><p class=\"text-right\" >Commented by ");
      out.print( dir.getUsername());
      out.write("(ID: ");
      out.print(user.getId() );
      out.write(")    Date is ");
      out.print(dir.getDate() );
      out.write("  CommentId is ");
      out.print(dir.getCommentid() );
      out.write(" </p></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-danger\" >Delete</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"panel panel-info\" style=\"margin: 20px 40px 20px 40px\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">My Comment</div>\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<form role=\"form\" action=\"/neu.edu.cs5200/CommentAction\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" placeholder=\"Write your comment\"  name=\"comment\"  rows=\"5\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div align=\"right\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" >Submit</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write(" \tif(");
      out.print( Global.username != null );
      out.write("){ \r\n");
      out.write(" \t\tdocument.getElementById(\"login\").innerHTML = \"");
      out.print( Global.username );
      out.write("\";\r\n");
      out.write(" \t\tvar login = document.getElementById(\"login\");\r\n");
      out.write(" \t\tlogin.setAttribute(\"href\", \"/neu.edu.cs5200/update.jsp\");\r\n");
      out.write(" \t\tdocument.getElementById(\"logout\").innerHTML = \"Logout\";\r\n");
      out.write(" \t\tvar logout = document.getElementById(\"logout\");\r\n");
      out.write(" \t\tlogout.setAttribute(\"href\", \"/neu.edu.cs5200/Login.jsp\");\t\t\r\n");
      out.write(" \t}\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
