/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-11-20 22:00:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import neu.edu.cs5200.*;

public final class testJS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
  GetACardByName get = new GetACardByName();
	String action = request.getParameter("action");
	String name = request.getParameter("name");
	
	Card card = new Card();
	
			
	
	if("search".equals(action)) {
		
		card = get.getCardByName(name);
		//System.out.println(card);
	}

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form >\r\n");
      out.write("\t<table class=\"table\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Please insert a name</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"name\" class=\"form-control\"  placeholder=\"name\"/></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td><button name=\"action\" value=\"search\" class=\"btn btn-success\" > Search</button></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<h5> The card's id is");
      out.print( card.getId() );
      out.write(" </h5>\r\n");
      out.write("\t<h5> The related card id is");
      out.print( card.getRelatedCardId() );
      out.write(" <h5>\r\n");
      out.write("\t<h5> The set number is ");
      out.print( card.getSetNumber() );
      out.write(" </h5>\r\n");
      out.write("\t<h5> The Name is ");
      out.print( card.getName() );
      out.write("</h5>\r\n");
      out.write("\t<h5> The search name is ");
      out.print( card.getSearchName() );
      out.write("</h5>\r\n");
      out.write("\t<h5> ");
      out.print( card.getDescription() );
      out.write("</h5>\r\n");
      out.write("\t<h5> ");
      out.print( card.getFlavor() );
      out.write("</h5>\r\n");
      out.write("\t<h5> The clolor is ");
      out.print( card.getColors() );
      out.write("</h5>\r\n");
      out.write("\t<h5> The mana cost is ");
      out.print( card.getManacost() );
      out.write("</h5>\r\n");
      out.write("\t<h5> The converted mana cost is ");
      out.print( card.getConvertedManaCost() );
      out.write("</h5>\r\n");
      out.write("\t<h5> Card set name : ");
      out.print( card.getCardSetName() );
      out.write("</h5>\r\n");
      out.write("\t<h5> Type : ");
      out.print( card.getType() );
      out.write("</h5>\r\n");
      out.write("\t<h5> Subtype : ");
      out.print( card.getSubType() );
      out.write("</h5>\r\n");
      out.write("\t<h5> Power : ");
      out.print( card.getPower() );
      out.write(" </h5>\r\n");
      out.write("\t</h5><img alt=\"\" src=\"http://api.mtgdb.info/content/card_images/");
      out.print( card.getId() );
      out.write(".jpeg\"></h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
